name: flutter_one
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.1
  audioplayers: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/fruits.png
    - assets/music.png
    - assets/waterme.png
    - assets/abc.png
    - assets/home.png
    - assets/task.png
    - assets/speaker.png
    - assets/background-anima.png
    - assets/background-another.png
    - assets/background_abc.png
    - assets/app-background.png
    - assets/top-background.png
    - assets/orange.png
    - assets/number.png
    - assets/cow.png
    - assets/clothes.png
    - assets/vehicle.png
    - assets/zebra.png
    - assets/arrow1.png
    - assets/arrow2.png
    - assets/apple.png
    - assets/background-main.png
    - assets/alphabet/fruits1.png
    - assets/alphabet/fruits2.png
    - assets/alphabet/fruits3.png
    - assets/alphabet/fruits4.png
    - assets/alphabet/fruits5.png
    - assets/alphabet/fruits6.png
    - assets/alphabet/fruits7.png
    - assets/alphabet/fruits9.png
    - assets/alphabet/fruits9.png
    - assets/fruits/fruits17.png
    - assets/alphabet/panda.png
    - assets/alphabet/yacht.png
    - assets/alphabet/xylophone.png
    - assets/alphabet/umbrella.png
    - assets/alphabet/violin.png
    - assets/alphabet/sun.png
    - assets/alphabet/queen.png
    - assets/alphabet/robot.png
    - assets/alphabet/nut.png
    - assets/alphabet/guitar.png
    - assets/alphabet/ice.png
    - assets/alphabet/jug.png
    - assets/animals/animal1.png
    - assets/animals/animal2.png
    - assets/animals/animal3.png
    - assets/animals/animal4.png
    - assets/animals/animal5.png
    - assets/animals/animal6.png
    - assets/animals/animal7.png
    - assets/animals/animal8.png
    - assets/animals/animal9.png
    - assets/animals/animal10.png
    - assets/animals/animal11.png
    - assets/animals/animal12.png
    - assets/animals/animal13.png
    - assets/animals/animal14.png
    - assets/animals/animal15.png
    - assets/animals/animal16.png
    - assets/animals/animal17.png
    - assets/animals/animal28.png
    - assets/animals/animal30.png
    - assets/animals/whale.png
    - assets/animals/octopus.png
    - assets/animals/kangaroo.png
    - assets/new-animal/bear.png
    - assets/new-animal/cat.png
    - assets/new-animal/donkey.png
    - assets/new-animal/elephant.png
    - assets/new-animal/giraffe.png
    - assets/new-animal/lion.png
    - assets/new-animal/monkey.png
    - assets/new-animal/panda-bear.png
    - assets/new-animal/fruit.png
    - assets/cars/bus.png
    - assets/cars/crane.png
    - assets/cars/fork_lif.png
    - assets/cars/motorcycle.png
    - assets/cars/ship.png
    - assets/cars/suv.png
    - assets/cars/train.png
    - assets/cars/truck.png
    - assets/song/mack.jpg
    - assets/song/animals.jpg
    - assets/song/john.jpg
    - assets/song/number.jpg
    - assets/sample.mp3
    - assets/click.mp3
    - assets/new.mp3
    - assets/a.mp3
    - assets/b.mp3
    - assets/c.mp3
    - assets/d.mp3
    - assets/e.mp3
    - assets/f.mp3
    - assets/g.mp3
    - assets/h.mp3
    - assets/i.mp3
    - assets/j.mp3
    - assets/k.mp3
    - assets/l.mp3
    - assets/m.mp3
    - assets/n.mp3
    - assets/o.mp3
    - assets/p.mp3
    - assets/q.mp3
    - assets/r.mp3
    - assets/s.mp3
    - assets/t.mp3
    - assets/u.mp3
    - assets/v.mp3
    - assets/w.mp3
    - assets/x.mp3
    - assets/y.mp3
    - assets/z.mp3
    - assets/number.mp3
    - assets/new-animal/snake.png
    - assets/fruits/fruits1.png
    - assets/fruits/fruits2.png
    - assets/fruits/fruits3.png
    - assets/fruits/fruits4.png
    - assets/fruits/fruits5.png
    - assets/fruits/fruits6.png
    - assets/fruits/fruits7.png
    - assets/fruits/fruits8.png
    - assets/fruits/fruits9.png
    - assets/fruits/fruits10.png
    - assets/music/hand.png
    - assets/teacher.png
    - assets/books_bottom.png
    - assets/aeiou.png
    - assets/swahili_assets/marriage.png
    - assets/swahili_assets/speaker.png
    - assets/swahili_assets/flower.png
    - assets/swahili_assets/screem.png
    - assets/swahili_assets/baba.png
    - assets/swahili_assets/chai.png
    - assets/swahili_assets/dada.png
    - assets/swahili_assets/fagio.png
    - assets/swahili_assets/gari.png
    - assets/swahili_assets/hoho.png
    - assets/swahili_assets/kuku.png
    - assets/swahili_assets/gauni.png
    - assets/swahili_assets/lala.png
    - assets/swahili_assets/mama.png
    - assets/swahili_assets/nazi.png
    - assets/swahili_assets/ruka.png
    - assets/swahili_assets/saa.png
    - assets/swahili_assets/taa.png
    - assets/swahili_assets/viatu.png
    - assets/swahili_assets/yai.png
    - assets/swahili_assets/zeze.png
    - assets/cat.mp3
    - assets/cow.mp3
    - assets/elephant.mp3
    - assets/girrafe.mp3
    - assets/lion1.mp3
    - assets/monkey.mp3
    - assets/panda.mp3
    - assets/snake.mp3
    - assets/zebra.mp3
    - assets/irabu_a.mp3
    - assets/irabu_e.mp3
    - assets/irabu_i.mp3
    - assets/irabu_o.mp3
    - assets/irabu_u.mp3
    - assets/clothers_folder/dress.png
    - assets/clothers_folder/shirt.png
    - assets/clothers_folder/shorts.png
    - assets/swahili_assets/finger.png
    - assets/swahili_assets/finger_new.png
    - assets/irabu_a.mp3
    - assets/irabu_e.mp3
    - assets/irabu_i.mp3
    - assets/irabu_o.mp3
    - assets/irabu_u.mp3
    - assets/ba.mp3
    - assets/be.mp3
    - assets/bi.mp3
    - assets/bo.mp3
    - assets/bu.mp3
    - assets/cha.mp3
    - assets/che.mp3
    - assets/chi.mp3
    - assets/cho.mp3
    - assets/chu.mp3
    - assets/da.mp3
    - assets/de.mp3
    - assets/di.mp3
    - assets/do.mp3
    - assets/du.mp3
    - assets/fa.mp3
    - assets/fe.mp3
    - assets/fi.mp3
    - assets/fo.mp3
    - assets/fu.mp3
    - assets/ga.mp3
    - assets/ge.mp3
    - assets/gi.mp3
    - assets/go.mp3
    - assets/gu.mp3
    - assets/ha.mp3
    - assets/he.mp3
    - assets/hi.mp3
    - assets/ho.mp3
    - assets/hu.mp3
    - assets/ja.mp3
    - assets/je.mp3
    - assets/ji.mp3
    - assets/jo.mp3
    - assets/ju.mp3
    - assets/ka.mp3
    - assets/ke.mp3
    - assets/ki.mp3
    - assets/ko.mp3
    - assets/ku.mp3
    - assets/la.mp3
    - assets/le.mp3
    - assets/li.mp3
    - assets/lo.mp3
    - assets/lu.mp3
    - assets/ma.mp3
    - assets/me.mp3
    - assets/mi.mp3
    - assets/mo.mp3
    - assets/mu.mp3
    - assets/na.mp3
    - assets/ne.mp3
    - assets/ni.mp3
    - assets/no.mp3
    - assets/nu.mp3
    - assets/pa.mp3
    - assets/pe.mp3
    - assets/pi.mp3
    - assets/po.mp3
    - assets/pu.mp3
    - assets/ra.mp3
    - assets/re.mp3
    - assets/ri.mp3
    - assets/ro.mp3
    - assets/ru.mp3
    - assets/sa.mp3
    - assets/se.mp3
    - assets/si.mp3
    - assets/so.mp3
    - assets/su.mp3
    - assets/ta.mp3
    - assets/te.mp3
    - assets/ti.mp3
    - assets/to.mp3
    - assets/tu.mp3
    - assets/va.mp3
    - assets/ve.mp3
    - assets/vi.mp3
    - assets/vo.mp3
    - assets/vu.mp3
    - assets/wa.mp3
    - assets/we.mp3
    - assets/wi.mp3
    - assets/wo.mp3
    - assets/wu.mp3
    - assets/ya.mp3
    - assets/ye.mp3
    - assets/yo.mp3
    - assets/yu.mp3
    - assets/za.mp3
    - assets/ze.mp3
    - assets/zi.mp3
    - assets/zo.mp3
    - assets/zu.mp3
    - assets/maneno_babu.mp3
    - assets/maneno_chai.mp3
    - assets/maneno_dada.mp3
    - assets/maneno_fagio.mp3
    - assets/maneno_gari.mp3
    - assets/maneno_gauni.mp3
    - assets/maneno_hoho.mp3
    - assets/maneno_kuku.mp3
    - assets/maneno_lala.mp3
    - assets/maneno_mama.mp3
    - assets/maneno_nazi.mp3
    - assets/maneno_ruka.mp3
    - assets/maneno_saa.mp3
    - assets/maneno_taa.mp3
    - assets/maneno_viatu.mp3
    - assets/maneno_yai.mp3
    - assets/maneno_zeze.mp3



    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Mansalva
       fonts:
         - asset: fonts/Mansalva-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Comic
       fonts:
         - asset: fonts/Comic-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
